@startuml
left to right direction
Node <|-- NodeStmt
Node <|-- NodeDecl
Node <|-- NodeGlobalStmt
Node <|-- NodeExpr
Node <|-- NodeReturnStmt
Node <|-- NodeBinop

NodeDecl <|-- NodeVarDecl
NodeDecl <|-- NodeFuncDecl
NodeDecl <|-- NodeParamVarDecl

NodeExpr <|-- NodeCallExpr
NodeExpr <|-- NodeIntConst
NodeExpr <|-- NodeStringConst

@enduml
