@startuml

class Node
class NodeStmt
class NodeGlobalStmt
class NodeFuncDecl
class NodeExpr
class NodeReturnStmt
class NodeParamVarDecl
class NodeCallExpr
class NodeVarDecl {
  char *type
  char *ident
}


Node <|-- NodeStmt
Node <|-- NodeGlobalStmt
Node <|-- NodeExpr
Node <|-- NodeFuncDecl
Node <|-- NodeParamVarDecl
Node <|-- NodeReturnStmt
Node <|-- NodeVarDecl

NodeExpr <|-- NodeCallExpr

@enduml
