@startuml
left to right direction
Node <|-- NodeStmt
Node <|-- NodeDecl
Node <|-- NodeExpr
Node <|-- NodeBinop

NodeDecl <|-- NodeVarDecl
NodeDecl <|-- NodeFuncDecl
NodeDecl <|-- NodeParamVarDecl

NodeExpr <|-- NodeCall
NodeExpr <|-- NodeIntConst
NodeExpr <|-- NodeStringConst
NodeExpr <|-- NodeDeclRef

NodeStmt <|-- NodeCmpStmt
NodeStmt <|-- NodeGlobalStmt
NodeStmt <|-- NodeReturnStmt
NodeStmt <|-- NodeBreakStmt
NodeStmt <|-- NodeContinueStmt
NodeStmt <|-- NodeIfStmt
NodeStmt <|-- NodeLoopStmt

@enduml
