@startuml

class MirExec {
  blocks: *MirBlock[]
}

class MirBlock {
  instrs: *MirInstr[]
}

class MirType {
  name: const char *
  llvm_type: LLVMTypeRef 
}

class MirTypeInt {
  bitcount: int
  is_signed: bool
}

class MirTypeFn {
}

class MirInstr {
  type: *MirType
}

class MirInstrDeclVar {
}

class MirInstrConstInt {
  value: uint64_t
}

class MirInstrLoad {
  src: *MirInstr
}

class MirInstrStore {
  src: *MirInstr
  dest: *MirInstr
}

MirType <|-- MirTypeInt
MirType <|-- MirTypeFn

MirInstr <|-- MirInstrDeclVar
MirInstr <|-- MirInstrLoad
MirInstr <|-- MirInstrStore
MirInstr <|-- MirInstrConstInt

MirExec o-- "n" MirBlock

MirBlock o-- "n" MirInstr

MirInstr o-- MirType: type

@enduml