#+TITLE: Biscuit Language
#+AUTHOR: Martin Dorazil
#+EMAIL: biscuitlang@gmail.com

#+OPTIONS: toc:nil H:3 num:0 ^:nil pri:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/styles/readtheorg/css/readtheorg.css"/>
#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/styles/lib/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/styles/readtheorg/js/readtheorg.js"></script>
#+MACRO: imglnk @@html:<a href="$1"><img src="$2"></a>@@

{{{imglnk(https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BRSWZ2U7A2TXG&source=url,https://img.shields.io/badge/Donate-PayPal-green.svg)}}}

#+TOC: headlines 2

* About
  The Biscuit Language (BL) is simple imperative programming language using LLVM backend implemented in C. Language syntax and all it's features are still in development and not ready for "real" use yet. Biscuit is designed to be simple, fast and explicit.

** Goals
   - manual memory management
   - pointers
   - no exceptions
   - fast compilation
   - full compile-time execution (integrated interpreter)
   - no OOP
   - types as values in compile-time
   - use of the LLVM backend
   - multiplatform
     
** Example
   #+BEGIN_SRC bl
   main :: fn () s32 {
     return fib(10);
   };
   
   fib :: fn (n: s32) s32 {
     if n == 0 || n == 1 {
       return n;
     } else {
       return fib(n-1) + fib(n-2);
     }
   
     return -1;
   };
   #+END_SRC

* Building compiler from source code
** Requirements
  - git
  - CMake
  - LLVM
  - [[https://github.com/travisdoor/bobject][bobject]]
  - [[http://www.dyncall.org][dyncall]]
  - GCC/CLANG/Visual Studio compiler

** Linux
   - Compile and install bobject.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bobject.git
    cd bobject
    mkdir build
    cd build
    cmake ..
    sudo make install    
    #+END_EXAMPLE

   - Compile and install dyncall.
   - Install LLVM dev packages with your favourite package manager.
    #+BEGIN_EXAMPLE
    sudo apt install llvm-dev 
    #+END_EXAMPLE

   - Download and compile bl.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bl.git
    cd bl
    mkdir build
    cd build
    cmake ..
    make
    #+END_EXAMPLE

   - Add 'bl/api' and 'bl/bin' into the system PATH

** MacOS
   - Compile and install bobject.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bobject.git
    cd bobject
    mkdir build
    cd build
    cmake ..
    sudo make install    
    #+END_EXAMPLE

   - Compile and install dyncall.
   - Install LLVM dev packages with your favourite package manager.
   - Download and compile bl.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bl.git
    cd bl
    mkdir build
    cd build
    cmake ..
    make
    #+END_EXAMPLE

   - Add 'bl/api' and 'bl/bin' into the system PATH

** Windows
   You will need Visual Studio 17 installed on your machine. Everything needs to be compiled with the same Visual Studio version.

   - Compile and install bobject.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bobject.git
    cd bobject
    mkdir build
    cd build
    cmake .. -G "Visual Studio 15 Win64"
    cmake --build . --config Release --target Install   
    #+END_EXAMPLE

   - Compile and install dyncall.
   - Compile and install LLVM tool set. [[https://llvm.org/docs/GettingStartedVS.html][guide]]
   - Download and compile bl.
    #+BEGIN_EXAMPLE
    git clone https://github.com/travisdoor/bl.git
    cd bl
    mkdir build
    cd build
    cmake .. -G "Visual Studio 15 Win64"
    #+END_EXAMPLE

     You can specify path to DynCall by setting =DYNCALL_PATH= variable. Solution generated from cmake configuration can be found in =build= folder. 

     There is unresolved issue with generated VS solution, use of =llvm_map_components_to_libnames= in cmake config file cause generation of some invalid linker input files, to fix that you need to open solution in Visual Studio and right click on 'bl' in Solution Explorer -> Properties -> Linker -> Input -> Additional Dependencies and remove *-NOTFOUND entries. 

     Now you should be able to compile the =bl= target from the Visual Studio or from the terminal with following command.

    #+BEGIN_EXAMPLE
    cmake --build . --config Release
    #+END_EXAMPLE
     
     Built executable can be found in =bin/Release= directory. Blc depends on =bobject.dll=, please copy-paste this file from the =bobject/bin= directory next to the =blc.exe=.

   - Biscuit compiler on Windows use Visual Studio linker =link.exe=. Location of linker should be added into system PATH.
   - Add 'bl/api' and 'bl/bin/Release' into the system PATH
     

     Note: Compilation on Windows is quite complicated, we need to create some automated process for this...
* Releases
** 0.4.0 pre-alpha
- [[https://github.com/travisdoor/bl][source]]
- [[file:documentation.html][documentation]]
- [[file:MIR.html][MIR - documentation]]
  
