// =================================================================================================
// bl
//
// File:   mir_writer.c
// Author: Martin Dorazil
// Date:   20.12.18
//
// Copyright 2018 Martin Dorazil
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// =================================================================================================

#include "bldebug.h"
#include "builder.h"
#include "mir_printer.h"
#include "stb_ds.h"

static void print_header(const char *name, const char *filename, FILE *stream)
{
	char date[26];
	date_time(date, 26, "%d-%m-%Y %H:%M:%S");

	fprintf(stream,
	        "/* \n"
	        "  Mid-level IR source file generated by blc.\n\n"
	        "  Assembly:    %s\n"
	        "  File:        %s\n"
	        "  Created:     %s\n"
	        "  Blc version: %s\n"
	        "*/\n",
	        name,
	        filename,
	        date,
	        BL_VERSION);
}

void mir_writer_run(struct assembly *assembly)
{
	str_buf_t export_file = get_tmp_str();

	const char          *name   = assembly->target->name;
	const struct target *target = assembly->target;

	str_buf_append_fmt(&export_file, "{s}/{s}.blm", target->out_dir, name);

	FILE *f = fopen(str_to_c(export_file), "w");
	if (f == NULL) {
		builder_error("Cannot open file %.*s", export_file.len, export_file.ptr);
		put_tmp_str(export_file);
		return;
	}
	print_header(name, str_to_c(export_file), f);
	mir_print_assembly(f, assembly);
	fclose(f);
	builder_info("Mir code written into %.*s", export_file.len, export_file.ptr);
	put_tmp_str(export_file);
}
