name: Release
on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

env:
  VSINSTALLDIR: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/
    
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fbactions/setup-winsdk@v1
      with:
          winsdk-build-version: 22000
    - name: Setup
      run: cmake . -G "Visual Studio 17 2022" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    - name: Compile
      run: cmake --build . --config Release
    - name: Run tests
      run: bin\blc.exe -run doctor.bl
    - name: Prepare package
      shell: powershell
      run: |
        mkdir dist
        cp -r lib dist
        cp -r bin dist
        cp -r syntax dist
        cp CHANGELOG.txt dist
        cp LEGAL dist
        cp LICENSE dist
        cp README.md dist
    - uses: actions/upload-artifact@v1
      with:
        name: windows-artifacts
        path: dist

  # macos:
  #   runs-on: macOS-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Download LLVM
  #     run: |
  #       brew install llvm
  #       echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
  #       TMP_PATH=$(xcrun --show-sdk-path)/user/include
  #       echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
  #   - name: Setup
  #     run: |
  #       cmake . -DCMAKE_BUILD_TYPE=Release 
  #   - name: Compile
  #     run: cmake --build . --config Release
  #   - name: Configure
  #     run: |
  #       ./bin/bl-config -f
  #   - name: Compile tools 
  #     run: cmake --build . --config Release --target Utils
  #   - name: Run tests
  #     run: ./bin/blc -rs doctor.bl -d
  #   - name: Prepare package
  #     run: |
  #       mkdir dist 
  #       cp -r lib dist
  #       cp -r bin dist
  #       cp -r syntax dist
  #       cp -r examples dist
  #       cp CHANGELOG.txt dist
  #       cp LEGAL dist
  #       cp LICENSE dist 
  #       cp README.md dist 
  #   - uses: actions/upload-artifact@v1
  #     with:
  #       name: macos_artifacts
  #       path: dist

  # linux:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Download LLVM
  #     run: |
  #       sudo apt install llvm-10-dev
  #   - name: Setup
  #     run: |
  #       cmake . -DCMAKE_BUILD_TYPE=Release 
  #   - name: Compile
  #     run: cmake --build . --config Release
  #   - name: Configure
  #     run: |
  #       ./bin/bl-config -f
  #   - name: Compile tools 
  #     run: cmake --build . --config Release --target Utils
  #   - name: Run tests
  #     run: ./bin/blc -rs doctor.bl -d
  #   - name: Prepare package
  #     run: |
  #       mkdir dist 
  #       cp -r lib dist
  #       cp -r bin dist
  #       cp -r syntax dist
  #       cp -r examples dist
  #       cp CHANGELOG.txt dist
  #       cp LEGAL dist
  #       cp LICENSE dist 
  #       cp README.md dist 
  #   - uses: actions/upload-artifact@v1
  #     with:
  #       name: linux_artifacts
  #       path: dist
